### PR TITLE
A few things here and there...

### PR DESCRIPTION
**Pull request by sgeto**

### CODE REVIEW

**Comment by gvanem** [comment]
My latest Visual Studio doesn't have a single `amd64` sub-directory, but `x64`. So why is `amd64` more correct? In fact I don't have a single `amd64` sub-directory *anywhere*.

**Comment by sgeto** [comment]
I'm not yet on the VS2017 train. I only have the build tools, which I rarely use,
But now that you're saying it I checked and you're right, they changed name of the 64bit subdirs to x64 latest version of VS:

```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Users\Ali\Source>echo %lib%
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.11.25503\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x64;
```

Why would they? Don't know what to make of this...

**Comment by gvanem** [comment]
> In fact I don't have a single amd64 sub-directory anywhere.

That was wrong. I do have some. 

> Why would they? Don't know what to make of this...

The new style of these paths is a bit confusing. But now MS put both the **WindowsKit** version and the **cl** version in the paths.

**Comment by gvanem** [comment]
I'm not any git expert, but here is what I did:

* Did the `install` PR by hand locally.
* A `git commit --author autostart.ini@gmail.com Makefile.vc6`.
* A `git push` shows https://github.com/gvanem/wsock-trace/commit/83fcc060463c5af1251e6e6351c1acbc65eba354.

Looks okay to me. So I guess I'll do **Close and comment** on this PR now?

**Comment by sgeto** [comment]
Looks good to me. I got two things:

- install must depend on all now
- I also added a nmake help target

You know what, I hand them in separately. Let me close this.

**Pull request closed without merging**
